### ISSUE TITLE
Release under a free license please

### ISSUE THREAD

**Issue by McSinyx** [Huy-Ngo/font-changer#1]
I'd appreciate if this get released under AGPLv3+ or any other free software license, e.g. MIT, BSD, etc.

**Comment by Huy-Ngo** [comment]
@McSinyx This app is still on progress, so I can't release already. I didn't design the logo for the app but used the one in the tutorial. Thanks for the suggestion anyway.

**Comment by Huy-Ngo** [comment]
Also it's a Chrome extension so I'm not sure if it's able to publish as a free software

**Comment by McSinyx** [comment]
> Also it's a Chrome extension so I'm not sure if it's able to publish as a free software

Yes you can (since all docs by Google on extensions are CC-BY and Chromium--which you might link dynamically--is free software).

> This app is still on progress, so I can't release already.

Just remember you can never tell if a small piece of code could turn out to be useful for many other people d-:

**Comment by McSinyx** [comment]
Since MIT was chosen, I think this issue is solved by now.  Some small suggestions though:

* Feel free to list your name in the header in Unicode: It's 2019, if one's machine does not support it, it's their problem.
* Plain texts (e.g. `LICENSE` and source files) are conventionally wrapped by a width of choice, somewhere between 80 to 120 columns.

Cheers!
